services:
  helloworld:
    build:
      context: ./hello-world 
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.helloworld.entrypoints=web" # required
      - "traefik.http.routers.helloworld.rule=Host(`backend.example.com`) && Path(`/`)" # required
      - "traefik.http.services.helloworld.loadbalancer.server.port=8000" # required
      - "traefik.http.services.helloworld.loadbalancer.healthCheck.path=/health" # optional
      - "traefik.http.services.helloworld.loadbalancer.healthCheck.interval=10s" # optional
      - "traefik.http.services.helloworld.loadbalancer.healthCheck.timeout=1s" # optional

      - "traefik.http.services.helloworld.loadbalancer.healthCheck.scheme=http" # optional
      - "traefik.http.services.helloworld.loadbalancer.healthCheck.mode=http" # optional
      - "traefik.http.services.helloworld.loadbalancer.healthCheck.hostname=backend.example.com" # optional
      - "traefik.http.services.helloworld.loadbalancer.healthCheck.port=8000" # optional

      - "traefik.http.services.helloworld.loadbalancer.healthCheck.headers.My-Custom-Header=foo" # optional
      - "traefik.http.services.helloworld.loadbalancer.healthCheck.headers.My-Header=bar" # optional
      - "traefik.http.services.helloworld.loadbalancer.healthCheck.followRedirects=true" # optional
      - "traefik.http.services.helloworld.loadbalancer.healthCheck.method=GET" # optional
      - "traefik.http.services.helloworld.loadbalancer.healthCheck.status=200" # optional
      # XMPP TCP
      - traefik.tcp.routers.helloworld-xmpp.rule=HostSNI(`*`)
      - traefik.tcp.routers.helloworld-xmpp.entrypoints=xmpp
      - traefik.tcp.services.helloworld-xmpp.loadbalancer.server.port=5222
      # XMPP Secure TCP
      - traefik.tcp.routers.helloworld-xmpp-secure.rule=HostSNI(`*`)
      - traefik.tcp.routers.helloworld-xmpp-secure.entrypoints=xmpp-secure
      - traefik.tcp.services.helloworld-xmpp-secure.loadbalancer.server.port=5223
    deploy:
      replicas: 2
    restart: unless-stopped
    environment:
      RETURN_200: 98
      RETURN_400: 1
      RETURN_500: 1
    #   SUPER_PUPER_SECRET_KEY: ${SUPER_SECRET_KEY}
    networks:
      - traefik
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s

  helloworld-front:
    build:
      context: ./hello-world-front
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.helloworld-front.entrypoints=web" # required
      - "traefik.http.routers.helloworld-front.rule=Host(`frontend.example.com`)" # required
      - "traefik.http.services.helloworld-front.loadbalancer.server.port=80" # required
      - "traefik.http.services.helloworld-front.loadbalancer.healthCheck.path=/" # optional
      - "traefik.http.services.helloworld-front.loadbalancer.healthCheck.interval=10s" # optional
      - "traefik.http.services.helloworld-front.loadbalancer.healthCheck.timeout=1s" # optional
    deploy:
      replicas: 2
    restart: unless-stopped
    networks:
      - traefik


# Previously, all Traefik config was mounted from one folder.
# To support static config too, we now load static config as a dedicated file
# and mount dynamic config as a dedicated directory, because file provider watch
# is reliable for dynamic updates only when the dynamic config is mounted as a folder.
  traefik-proxy:
    image: traefik:v3.3.4
    command:
      - --configFile=/etc/traefik/traefik.static.yml
      # - --providers.docker=true (optional for specific needs)
      # - --providers.docker.endpoint=tcp://socket-proxy:2375
      # - --providers.docker.exposedbydefault=false
    restart: unless-stopped
    ports:
      - "8000:80"
      - "8080:8080"
      - "5222:5222"
      - "5223:5223"
    volumes:
      - ./traefik-static/traefik.static.yml:/etc/traefik/traefik.static.yml:ro
      - ./traefik:/etc/traefik/dynamic:ro
    networks:
      - traefik
    # depends_on:
    #   - socket-proxy

  # socket-proxy: (optional for specific needs)
  #   image: tecnativa/docker-socket-proxy
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - traefik
  #   environment:
  #     CONTAINERS: 1
  #   restart: unless-stopped

networks:
  traefik:
    driver: bridge