---
tls:
  certificates:
    - certFile: "/certs/certificate.crt"
      keyFile: "/certs/private.key"
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/certificate.crt"
        keyFile: "/certs/private.key"